package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CandidateMaster generated by hbm2java
 */
public class CandidateMaster implements java.io.Serializable {

	private int candidateId;
	private PartyRegistry partyRegistry;
	private ElectionMaster electionMaster;
	private String firstName;
	private String lastName;
	private Date dateOfBirth;
	private String nric;
	private Character gender;
	private Set<CandidateConstituencyMapping> candidateConstituencyMappings = new HashSet<CandidateConstituencyMapping>(
			0);

	public CandidateMaster() {
	}

	public CandidateMaster(int candidateId) {
		this.candidateId = candidateId;
	}

	public CandidateMaster(int candidateId, PartyRegistry partyRegistry,
			ElectionMaster electionMaster, String firstName, String lastName,
			Date dateOfBirth, String nric, Character gender,
			Set<CandidateConstituencyMapping> candidateConstituencyMappings) {
		this.candidateId = candidateId;
		this.partyRegistry = partyRegistry;
		this.electionMaster = electionMaster;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dateOfBirth = dateOfBirth;
		this.nric = nric;
		this.gender = gender;
		this.candidateConstituencyMappings = candidateConstituencyMappings;
	}

	public int getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(int candidateId) {
		this.candidateId = candidateId;
	}

	public PartyRegistry getPartyRegistry() {
		return this.partyRegistry;
	}

	public void setPartyRegistry(PartyRegistry partyRegistry) {
		this.partyRegistry = partyRegistry;
	}

	public ElectionMaster getElectionMaster() {
		return this.electionMaster;
	}

	public void setElectionMaster(ElectionMaster electionMaster) {
		this.electionMaster = electionMaster;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getNric() {
		return this.nric;
	}

	public void setNric(String nric) {
		this.nric = nric;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public Set<CandidateConstituencyMapping> getCandidateConstituencyMappings() {
		return this.candidateConstituencyMappings;
	}

	public void setCandidateConstituencyMappings(
			Set<CandidateConstituencyMapping> candidateConstituencyMappings) {
		this.candidateConstituencyMappings = candidateConstituencyMappings;
	}

}
