package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * ConstituencyPartyMapping generated by hbm2java
 */
public class ConstituencyPartyMapping implements java.io.Serializable {

	private ConstituencyPartyMappingId id;
	private PartyRegistry partyRegistry;
	private ConstituencyMaster constituencyMaster;

	public ConstituencyPartyMapping() {
	}

	public ConstituencyPartyMapping(ConstituencyPartyMappingId id) {
		this.id = id;
	}

	public ConstituencyPartyMapping(ConstituencyPartyMappingId id,
			PartyRegistry partyRegistry, ConstituencyMaster constituencyMaster) {
		this.id = id;
		this.partyRegistry = partyRegistry;
		this.constituencyMaster = constituencyMaster;
	}

	public ConstituencyPartyMappingId getId() {
		return this.id;
	}

	public void setId(ConstituencyPartyMappingId id) {
		this.id = id;
	}

	public PartyRegistry getPartyRegistry() {
		return this.partyRegistry;
	}

	public void setPartyRegistry(PartyRegistry partyRegistry) {
		this.partyRegistry = partyRegistry;
	}

	public ConstituencyMaster getConstituencyMaster() {
		return this.constituencyMaster;
	}

	public void setConstituencyMaster(ConstituencyMaster constituencyMaster) {
		this.constituencyMaster = constituencyMaster;
	}

}
