package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ConstituencyMaster generated by hbm2java
 */
public class ConstituencyMaster implements java.io.Serializable {

	private String constituencyId;
	private ElectionMaster electionMaster;
	private String constituencyName;
	private Set<ConstituencyPartyMapping> constituencyPartyMappings = new HashSet<ConstituencyPartyMapping>(
			0);
	private Set<ConstituencyArea> constituencyAreas = new HashSet<ConstituencyArea>(
			0);
	private Set<CandidateConstituencyMapping> candidateConstituencyMappings = new HashSet<CandidateConstituencyMapping>(
			0);

	public ConstituencyMaster() {
	}

	public ConstituencyMaster(String constituencyId) {
		this.constituencyId = constituencyId;
	}

	public ConstituencyMaster(String constituencyId,
			ElectionMaster electionMaster, String constituencyName,
			Set<ConstituencyPartyMapping> constituencyPartyMappings,
			Set<ConstituencyArea> constituencyAreas,
			Set<CandidateConstituencyMapping> candidateConstituencyMappings) {
		this.constituencyId = constituencyId;
		this.electionMaster = electionMaster;
		this.constituencyName = constituencyName;
		this.constituencyPartyMappings = constituencyPartyMappings;
		this.constituencyAreas = constituencyAreas;
		this.candidateConstituencyMappings = candidateConstituencyMappings;
	}

	public String getConstituencyId() {
		return this.constituencyId;
	}

	public void setConstituencyId(String constituencyId) {
		this.constituencyId = constituencyId;
	}

	public ElectionMaster getElectionMaster() {
		return this.electionMaster;
	}

	public void setElectionMaster(ElectionMaster electionMaster) {
		this.electionMaster = electionMaster;
	}

	public String getConstituencyName() {
		return this.constituencyName;
	}

	public void setConstituencyName(String constituencyName) {
		this.constituencyName = constituencyName;
	}

	public Set<ConstituencyPartyMapping> getConstituencyPartyMappings() {
		return this.constituencyPartyMappings;
	}

	public void setConstituencyPartyMappings(
			Set<ConstituencyPartyMapping> constituencyPartyMappings) {
		this.constituencyPartyMappings = constituencyPartyMappings;
	}

	public Set<ConstituencyArea> getConstituencyAreas() {
		return this.constituencyAreas;
	}

	public void setConstituencyAreas(Set<ConstituencyArea> constituencyAreas) {
		this.constituencyAreas = constituencyAreas;
	}

	public Set<CandidateConstituencyMapping> getCandidateConstituencyMappings() {
		return this.candidateConstituencyMappings;
	}

	public void setCandidateConstituencyMappings(
			Set<CandidateConstituencyMapping> candidateConstituencyMappings) {
		this.candidateConstituencyMappings = candidateConstituencyMappings;
	}

}
