package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * ConstituencyArea generated by hbm2java
 */
public class ConstituencyArea implements java.io.Serializable {

	private ConstituencyAreaId id;
	private PollingstationMaster pollingstationMaster;
	private ConstituencyMaster constituencyMaster;

	public ConstituencyArea() {
	}

	public ConstituencyArea(ConstituencyAreaId id) {
		this.id = id;
	}

	public ConstituencyArea(ConstituencyAreaId id,
			PollingstationMaster pollingstationMaster,
			ConstituencyMaster constituencyMaster) {
		this.id = id;
		this.pollingstationMaster = pollingstationMaster;
		this.constituencyMaster = constituencyMaster;
	}

	public ConstituencyAreaId getId() {
		return this.id;
	}

	public void setId(ConstituencyAreaId id) {
		this.id = id;
	}

	public PollingstationMaster getPollingstationMaster() {
		return this.pollingstationMaster;
	}

	public void setPollingstationMaster(
			PollingstationMaster pollingstationMaster) {
		this.pollingstationMaster = pollingstationMaster;
	}

	public ConstituencyMaster getConstituencyMaster() {
		return this.constituencyMaster;
	}

	public void setConstituencyMaster(ConstituencyMaster constituencyMaster) {
		this.constituencyMaster = constituencyMaster;
	}

}
