package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * ConstituencyPartyMappingId generated by hbm2java
 */
public class ConstituencyPartyMappingId implements java.io.Serializable {

	private Integer constituencyPartyMappingid;
	private String constituencyId;
	private String partyId;

	public ConstituencyPartyMappingId() {
	}

	public ConstituencyPartyMappingId(Integer constituencyPartyMappingid,
			String constituencyId, String partyId) {
		this.constituencyPartyMappingid = constituencyPartyMappingid;
		this.constituencyId = constituencyId;
		this.partyId = partyId;
	}

	public Integer getConstituencyPartyMappingid() {
		return this.constituencyPartyMappingid;
	}

	public void setConstituencyPartyMappingid(Integer constituencyPartyMappingid) {
		this.constituencyPartyMappingid = constituencyPartyMappingid;
	}

	public String getConstituencyId() {
		return this.constituencyId;
	}

	public void setConstituencyId(String constituencyId) {
		this.constituencyId = constituencyId;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConstituencyPartyMappingId))
			return false;
		ConstituencyPartyMappingId castOther = (ConstituencyPartyMappingId) other;

		return ((this.getConstituencyPartyMappingid() == castOther
				.getConstituencyPartyMappingid()) || (this
				.getConstituencyPartyMappingid() != null
				&& castOther.getConstituencyPartyMappingid() != null && this
				.getConstituencyPartyMappingid().equals(
						castOther.getConstituencyPartyMappingid())))
				&& ((this.getConstituencyId() == castOther.getConstituencyId()) || (this
						.getConstituencyId() != null
						&& castOther.getConstituencyId() != null && this
						.getConstituencyId().equals(
								castOther.getConstituencyId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this
						.getPartyId() != null && castOther.getPartyId() != null && this
						.getPartyId().equals(castOther.getPartyId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getConstituencyPartyMappingid() == null ? 0 : this
						.getConstituencyPartyMappingid().hashCode());
		result = 37
				* result
				+ (getConstituencyId() == null ? 0 : this.getConstituencyId()
						.hashCode());
		result = 37 * result
				+ (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		return result;
	}

}
