package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * ElectionResultsId generated by hbm2java
 */
public class ElectionResultsId implements java.io.Serializable {

	private int electionId;
	private int constituencyPartyMappingid;

	public ElectionResultsId() {
	}

	public ElectionResultsId(int electionId, int constituencyPartyMappingid) {
		this.electionId = electionId;
		this.constituencyPartyMappingid = constituencyPartyMappingid;
	}

	public int getElectionId() {
		return this.electionId;
	}

	public void setElectionId(int electionId) {
		this.electionId = electionId;
	}

	public int getConstituencyPartyMappingid() {
		return this.constituencyPartyMappingid;
	}

	public void setConstituencyPartyMappingid(int constituencyPartyMappingid) {
		this.constituencyPartyMappingid = constituencyPartyMappingid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElectionResultsId))
			return false;
		ElectionResultsId castOther = (ElectionResultsId) other;

		return (this.getElectionId() == castOther.getElectionId())
				&& (this.getConstituencyPartyMappingid() == castOther
						.getConstituencyPartyMappingid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getElectionId();
		result = 37 * result + this.getConstituencyPartyMappingid();
		return result;
	}

}
