package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * ElectionResults generated by hbm2java
 */
public class ElectionResults implements java.io.Serializable {

	private ElectionResultsId id;
	private Integer numberofvotes;
	private String status;
	private String checksum;

	public ElectionResults() {
	}

	public ElectionResults(ElectionResultsId id) {
		this.id = id;
	}

	public ElectionResults(ElectionResultsId id, Integer numberofvotes,
			String status, String checksum) {
		this.id = id;
		this.numberofvotes = numberofvotes;
		this.status = status;
		this.checksum = checksum;
	}

	public ElectionResultsId getId() {
		return this.id;
	}

	public void setId(ElectionResultsId id) {
		this.id = id;
	}

	public Integer getNumberofvotes() {
		return this.numberofvotes;
	}

	public void setNumberofvotes(Integer numberofvotes) {
		this.numberofvotes = numberofvotes;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getChecksum() {
		return this.checksum;
	}

	public void setChecksum(String checksum) {
		this.checksum = checksum;
	}

}
