package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * ConstituencyPartyMapping generated by hbm2java
 */
public class ElectionResultsBean implements java.io.Serializable {

	private String constituencyName;
	private String partyName;
	private Integer counter;
	
	public ElectionResultsBean() {
	}

	public ElectionResultsBean(String constituencyName, String partyName, Integer counter) {
			
		this.constituencyName = constituencyName;
		this.partyName = partyName;
		this.counter = counter;
		
	}

	public String getConstituencyName() {
		return this.constituencyName;
	}

	public void setConstituencyName(String constituencyName) {
		this.constituencyName = constituencyName;
	}
	
	public String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(String partyName) {
		this.partyName = partyName;
	}
	
	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

}
