package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PartyRegistry generated by hbm2java
 */
public class PartyBean implements java.io.Serializable {

	private Integer constituencyPartyMappingid;
	private String partyId;
	private String partyName;
	private byte[] partySymbol;
	private Date dateOfInception;
	private String status;	
	private Boolean selected;	

	public PartyBean() {
	}

	public PartyBean(Integer constituencyPartyMappingid, String partyId, String partyName, byte[] partySymbol,
			Date dateOfInception, String status, Boolean selected) {
			
		this.constituencyPartyMappingid = constituencyPartyMappingid;
		this.partyId = partyId;
		this.partyName = partyName;
		this.partySymbol = partySymbol;
		this.dateOfInception = dateOfInception;
		this.status = status;
		this.selected = selected;
		
	}

	public Integer getConstituencyPartyMappingid() {
		return this.constituencyPartyMappingid;
	}

	public void setConstituencyPartyMappingid(Integer constituencyPartyMappingid) {
		this.constituencyPartyMappingid = constituencyPartyMappingid;
	}
	
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(String partyName) {
		this.partyName = partyName;
	}

	public byte[] getPartySymbol() {
		return this.partySymbol;
	}

	public void setPartySymbol(byte[] partySymbol) {
		this.partySymbol = partySymbol;
	}

	public Date getDateOfInception() {
		return this.dateOfInception;
	}

	public void setDateOfInception(Date dateOfInception) {
		this.dateOfInception = dateOfInception;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	public Boolean getSelected() {
		return this.selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}
}
