package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PollingLogId generated by hbm2java
 */
public class PollingLogId implements java.io.Serializable {

	private String voterId;
	private Date dateOfVoting;

	public PollingLogId() {
	}

	public PollingLogId(String voterId, Date dateOfVoting) {
		this.voterId = voterId;
		this.dateOfVoting = dateOfVoting;
	}

	public String getVoterId() {
		return this.voterId;
	}

	public void setVoterId(String voterId) {
		this.voterId = voterId;
	}

	public Date getDateOfVoting() {
		return this.dateOfVoting;
	}

	public void setDateOfVoting(Date dateOfVoting) {
		this.dateOfVoting = dateOfVoting;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PollingLogId))
			return false;
		PollingLogId castOther = (PollingLogId) other;

		return ((this.getVoterId() == castOther.getVoterId()) || (this
				.getVoterId() != null && castOther.getVoterId() != null && this
				.getVoterId().equals(castOther.getVoterId())))
				&& ((this.getDateOfVoting() == castOther.getDateOfVoting()) || (this
						.getDateOfVoting() != null
						&& castOther.getDateOfVoting() != null && this
						.getDateOfVoting().equals(castOther.getDateOfVoting())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVoterId() == null ? 0 : this.getVoterId().hashCode());
		result = 37
				* result
				+ (getDateOfVoting() == null ? 0 : this.getDateOfVoting()
						.hashCode());
		return result;
	}

}
