package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PollingstationMaster generated by hbm2java
 */
public class PollingstationMaster implements java.io.Serializable {

	private String pollingStationId;
	private String pollingStationName;
	private String addressline1;
	private String addressline2;
	private Integer zipcode;
	private Set<ConstituencyArea> constituencyAreas = new HashSet<ConstituencyArea>(
			0);
	//private Set<VoterLogbook> voterLogbooks = new HashSet<VoterLogbook>(0);

	public PollingstationMaster() {
	}

	public PollingstationMaster(String pollingStationId) {
		this.pollingStationId = pollingStationId;
	}

	public PollingstationMaster(String pollingStationId,
			String pollingStationName, String addressline1,
			String addressline2, Integer zipcode,
			Set<ConstituencyArea> constituencyAreas//, Set<VoterLogbook> voterLogbooks
			) {
		this.pollingStationId = pollingStationId;
		this.pollingStationName = pollingStationName;
		this.addressline1 = addressline1;
		this.addressline2 = addressline2;
		this.zipcode = zipcode;
		this.constituencyAreas = constituencyAreas;
		//this.voterLogbooks = voterLogbooks;
	}

	public String getPollingStationId() {
		return this.pollingStationId;
	}

	public void setPollingStationId(String pollingStationId) {
		this.pollingStationId = pollingStationId;
	}

	public String getPollingStationName() {
		return this.pollingStationName;
	}

	public void setPollingStationName(String pollingStationName) {
		this.pollingStationName = pollingStationName;
	}

	public String getAddressline1() {
		return this.addressline1;
	}

	public void setAddressline1(String addressline1) {
		this.addressline1 = addressline1;
	}

	public String getAddressline2() {
		return this.addressline2;
	}

	public void setAddressline2(String addressline2) {
		this.addressline2 = addressline2;
	}

	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	public Set<ConstituencyArea> getConstituencyAreas() {
		return this.constituencyAreas;
	}

	public void setConstituencyAreas(Set<ConstituencyArea> constituencyAreas) {
		this.constituencyAreas = constituencyAreas;
	}

/*	public Set<VoterLogbook> getVoterLogbooks() {
		return this.voterLogbooks;
	}

	public void setVoterLogbooks(Set<VoterLogbook> voterLogbooks) {
		this.voterLogbooks = voterLogbooks;
	}*/

}
