package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * PollingLog generated by hbm2java
 */
public class PollingLog implements java.io.Serializable {

	private PollingLogId id;
	private VoterRegistry voterRegistry;

	public PollingLog() {
	}

	public PollingLog(PollingLogId id) {
		this.id = id;
	}

	public PollingLog(PollingLogId id, VoterRegistry voterRegistry) {
		this.id = id;
		this.voterRegistry = voterRegistry;
	}

	public PollingLogId getId() {
		return this.id;
	}

	public void setId(PollingLogId id) {
		this.id = id;
	}

	public VoterRegistry getVoterRegistry() {
		return this.voterRegistry;
	}

	public void setVoterRegistry(VoterRegistry voterRegistry) {
		this.voterRegistry = voterRegistry;
	}

}
