package sg.edu.nyp.evoting.beans;

// Generated Feb 7, 2015 7:06:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VoterRegistry generated by hbm2java
 */
public class VoterRegistry implements java.io.Serializable {

	private String voterId;
	private Integer zipcode;
	private String firstName;
	private String lastName;
	private String nric;
	private Date dateOfBirth;
	private Character gender;
	private String addressLine1;
	private String addressLine2;
	private String email;
	private Integer mobilePhone;
	private Date modifiedDate;
	private Set<PollingLog> pollingLogs = new HashSet<PollingLog>(0);

	public VoterRegistry() {
	}

	public VoterRegistry(String voterId) {
		this.voterId = voterId;
	}

	public VoterRegistry(String voterId, Integer zipcode, String firstName,
			String lastName, String nric, Date dateOfBirth, Character gender,
			String addressLine1, String addressLine2, String email,
			Integer mobilePhone, Date modifiedDate, Set<PollingLog> pollingLogs) {
		this.voterId = voterId;
		this.zipcode = zipcode;
		this.firstName = firstName;
		this.lastName = lastName;
		this.nric = nric;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.email = email;
		this.mobilePhone = mobilePhone;
		this.modifiedDate = modifiedDate;
		this.pollingLogs = pollingLogs;
	}

	public String getVoterId() {
		return this.voterId;
	}

	public void setVoterId(String voterId) {
		this.voterId = voterId;
	}

	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getNric() {
		return this.nric;
	}

	public void setNric(String nric) {
		this.nric = nric;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(Integer mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Set<PollingLog> getPollingLogs() {
		return this.pollingLogs;
	}

	public void setPollingLogs(Set<PollingLog> pollingLogs) {
		this.pollingLogs = pollingLogs;
	}

}
