package sg.edu.nyp.evoting.beans;

// Generated Feb 9, 2015 1:01:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * VoterLogbook generated by hbm2java
 */
public class VoterLogbook implements java.io.Serializable {

	private VoterLogbookId id;

	public VoterLogbook() {
	}

	public VoterLogbook(VoterLogbookId id) {
		this.id = id;
	}

	public VoterLogbookId getId() {
		return this.id;
	}

	public void setId(VoterLogbookId id) {
		this.id = id;
	}

}
